local keymap = require("kuuga.lib.keymap")

-- window management
keymap.map("n", "<Leader>ws", "<C-w>s", "Split window horizontally")
keymap.map("n", "<Leader>wv", "<C-w>v", "Split window vertically")
keymap.map("n", "<Leader>wn", "<C-w>n", "New empty file in a split")
keymap.map("n", "<Leader>wo", "<C-w>o", "Make the current window as the only one")
keymap.map("n", "<Leader>ww", "<C-w>w", "Move cursor to next window")
keymap.map("n", "<Leader>wj", "<C-w>j", "Move cursor to below window")
keymap.map("n", "<Leader>wk", "<C-w>k", "Move cursor to above window ")
keymap.map("n", "<Leader>wh", "<C-w>h", "Move cursor to left window")
keymap.map("n", "<Leader>wl", "<C-w>l", "Move cursor to right window")
keymap.map("n", "<Leader>wJ", "<C-w>J", "Move window to the very bottom")
keymap.map("n", "<Leader>wK", "<C-w>K", "Move window to the very top")
keymap.map("n", "<Leader>wH", "<C-w>H", "Move window to the far left")
keymap.map("n", "<Leader>wL", "<C-w>L", "Move window to the far right")
keymap.map("n", "<Leader>w=", "<C-w>=", "Make window equally high and wide (almost)")
keymap.map("n", "<Leader>w+", "<C-w>+", "Increase window height")
keymap.map("n", "<Leader>w-", "<C-w>-", "Decrease window height")
keymap.map("n", "<Leader>w<", "<C-w><", "Decrease window width")
keymap.map("n", "<Leader>w>", "<C-w>>", "Increase window width")
keymap.map("n", "<Leader>w|", "<C-w>|", "Make the window largest (not closing any)")
keymap.map("n", "<C-s>", "<cmd>update<CR>", "Quick save")
keymap.map("n", "<Leader>e", "<cmd>edit<CR>", "Quick re-edit")
keymap.map("n", "<Leader>qq", "<cmd>quit<CR>", "Quick quit")
keymap.map("n", "<Leader>qa", "<cmd>qall<CR>", "Quick quit all")
keymap.map("n", "<Leader>fqq", "<cmd>quit!<CR>", "Quick force quit")

keymap.map("n", "yoh", "<CMD>set hlsearch!<CR>", "Toggle highlight search")
keymap.map("n", "yos", "<CMD>set spell!<CR>", "Toggle spell check")
keymap.map("n", "yoc", "<CMD>set cursorcolumn!<CR>", "Toggle cursor column")
keymap.map("n", "yow", "<CMD>set wrap!<CR>", "Toggle line wrap")

keymap.map({ "i", "n" }, "<esc>", "<cmd>noh<cr><esc>", "Escape and clear hlsearch")
keymap.map("t", "<esc><esc>", "<C-\\><C-n>", "Enter normal mode")

keymap.map("n", "<Leader>lazy", "<CMD>Lazy<CR>", "Open Lazy.nvim")
