require("kuuga.checkversion")

vim.loader.enable()

require("kuuga.lib")
require("kuuga.ui2")
require("kuuga.delay-notify")
require("kuuga.settings")
require("kuuga.filetypes")
require("kuuga.keymaps")
require("kuuga.autocmds")
require("kuuga.plugin-hooks")
require("kuuga.colorscheme")
require("kuuga.lsp")
require("kuuga.diagnostic")
