local vimp = require("vimp")

-- window management
vimp.nnoremap("<Leader>ws", "<C-w>s")
vimp.nnoremap("<Leader>wv", "<C-w>v")
vimp.nnoremap("<Leader>wn", "<C-w>n")
vimp.nnoremap("<Leader>wo", "<C-w>o")
vimp.nnoremap("<Leader>wj", "<C-w>j")
vimp.nnoremap("<Leader>wk", "<C-w>k")
vimp.nnoremap("<Leader>wh", "<C-w>h")
vimp.nnoremap("<Leader>wl", "<C-w>l")
vimp.nnoremap("<Leader>wJ", "<C-w>J")
vimp.nnoremap("<Leader>wK", "<C-w>K")
vimp.nnoremap("<Leader>wH", "<C-w>H")
vimp.nnoremap("<Leader>wL", "<C-w>L")
vimp.nnoremap("<Leader>w=", "<C-w>=")
vimp.nnoremap("<Leader>w+", "<C-w>+")
vimp.nnoremap("<Leader>w-", "<C-w>-")
vimp.nnoremap("<Leader>w<", "<C-w><")
vimp.nnoremap("<Leader>w>", "<C-w>>")
vimp.nnoremap("<Leader>w|", "<C-w>|")

vimp.nnoremap("yoh", function()
	vim.opt.hlsearch = not vim.opt.hlsearch:get()
end)

vimp.nnoremap("yos", function()
	vim.opt.spell = not vim.opt.spell:get()
end)
