local gh = require("kuuga.lib.pack-source.gh")
vim.schedule(function()
	vim.pack.add({ gh("JoosepAlviste/nvim-ts-context-commentstring") })
	vim.pack.add({ gh("nvim-treesitter/nvim-treesitter") })
end)
